// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260523130012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("dotnet_store.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Elektronik",
                            Url = "elektronik"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p1.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 74999.0,
                            ProductName = "Apple iPhone 15 Pro"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p2.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 64999.0,
                            ProductName = "Samsung Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p3.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 34999.0,
                            ProductName = "Xiaomi 14 Pro"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p4.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 54999.0,
                            ProductName = "Apple iPhone 14"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p5.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 19999.0,
                            ProductName = "Samsung Galaxy A54"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p6.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 39999.0,
                            ProductName = "OnePlus 12"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p7.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 49999.0,
                            ProductName = "Google Pixel 8 Pro"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p8.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 44999.0,
                            ProductName = "Huawei P60 Pro"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p9.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 24999.0,
                            ProductName = "Realme GT 5 Pro"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p10.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 21999.0,
                            ProductName = "Motorola Edge 50 Pro"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "En son işlemci teknolojisi ve gelişmiş kamera sistemiyle donatılmış premium akıllı telefon. 5G bağlantı desteği, uzun pil ömrü ve yüksek yenileme hızlı ekranıyla günlük kullanımda üstün deneyim sunar.",
                            Image = "p11.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 29999.0,
                            ProductName = "Apple iPhone SE 3. Nesil"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p12.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 24999.0,
                            ProductName = "Bosch Çamaşır Makinesi 9 kg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p13.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 34999.0,
                            ProductName = "Arçelik No-Frost Buzdolabı"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p14.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 21999.0,
                            ProductName = "Samsung Bulaşık Makinesi"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p15.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 14999.0,
                            ProductName = "Vestel Solo Fırın"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p16.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 29999.0,
                            ProductName = "LG Inverter Klima 12000 BTU"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p17.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 27999.0,
                            ProductName = "Siemens Çamaşır Kurutma Makinesi"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p18.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 17999.0,
                            ProductName = "Bosch Derin Dondurucu"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p19.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 39999.0,
                            ProductName = "Arçelik Alttan Donduruculu Buzdolabı"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p20.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 17999.0,
                            ProductName = "Beko Bulaşık Makinesi"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p21.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 54999.0,
                            ProductName = "Miele Çamaşır Makinesi"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Enerji tasarruflu A+++ sınıfı inverter motor teknolojisiyle donatılmış ev elektroniği. Akıllı programlar, sessiz çalışma modu ve uzun ömürlü yapısıyla evinizde maksimum konfor sağlar.",
                            Image = "p22.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 22999.0,
                            ProductName = "Tefal Ankastre Fırın"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p23.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 4999.0,
                            ProductName = "Nike Air Force 1 Sneaker"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p24.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 3499.0,
                            ProductName = "Adidas Originals Hoodie"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p25.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 4499.0,
                            ProductName = "Levi's 501 Original Jeans"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p26.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 2999.0,
                            ProductName = "Tommy Hilfiger Polo Tişört"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p27.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 7999.0,
                            ProductName = "Zara Erkek Blazer Ceket"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p28.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 3499.0,
                            ProductName = "Mango Midi Elbise"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p29.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 3999.0,
                            ProductName = "H&M Kaban"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p30.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 2499.0,
                            ProductName = "Nike Dri-FIT Eşofman Altı"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p31.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 4499.0,
                            ProductName = "Adidas Stan Smith Sneaker"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p32.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 1499.0,
                            ProductName = "LC Waikiki Oversize Sweatshirt"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Description = "Premium kalite doğal kumaştan üretilen bu parça; şık kesimi ve konforlu yapısıyla öne çıkar. Günlük kullanımdan özel günlere kadar her stile uyum sağlayan çok yönlü bir seçim.",
                            Image = "p33.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 2499.0,
                            ProductName = "Marks & Spencer Slim Fit Gömlek"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p34.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 849.0,
                            ProductName = "La Roche-Posay Güneş Kremi SPF50"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p35.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 1199.0,
                            ProductName = "Clinique Moisture Surge 100H Krem"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p36.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 599.0,
                            ProductName = "MAC Retro Matte Kırmızı Ruj"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p37.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 3499.0,
                            ProductName = "Dior Sauvage Erkek Parfüm 100ml"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p38.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 4999.0,
                            ProductName = "Chanel No.5 Eau de Parfum 100ml"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p39.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 349.0,
                            ProductName = "Maybelline Sky High Maskara"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p40.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 249.0,
                            ProductName = "L'Oreal Elvive Argan Şampuan 400ml"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p41.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 449.0,
                            ProductName = "Nivea Q10 Plus Gece Kremi"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p42.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 1199.0,
                            ProductName = "NARS Natural Radiant Longwear Fondöten"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p43.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 549.0,
                            ProductName = "Vichy Micellar Su Hassas Cilt 400ml"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "Dermatolojik testlerden geçmiş, hipoalerjenik formülüyle tüm cilt tiplerine uygundur. Aktif bileşenleri ve nemlendirici içerikleriyle cildinizi besler, korur ve güzelleştirir.",
                            Image = "p44.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 3999.0,
                            ProductName = "Estee Lauder Advanced Night Repair Serum"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p45.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 119999.0,
                            ProductName = "Apple MacBook Pro 14 inc M3 Pro"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p46.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Price = 54999.0,
                            ProductName = "Samsung QLED 55 inc 4K Smart TV"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p47.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 8499.0,
                            ProductName = "Sony WH-1000XM5 Kablosuz Kulaklık"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p48.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 64999.0,
                            ProductName = "Apple iPad Pro 12.9 inc M2"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p49.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 84999.0,
                            ProductName = "Dell XPS 15 Intel Core i7 Laptop"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p50.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 3499.0,
                            ProductName = "Logitech MX Master 3S Mouse"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p51.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 8499.0,
                            ProductName = "Apple AirPods Pro 2. Nesil"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p52.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 34999.0,
                            ProductName = "Canon EOS R50 Aynasız Fotoğraf Makinesi"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p53.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 24999.0,
                            ProductName = "Sony PlayStation 5 Disk Sürücülü"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p54.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 17999.0,
                            ProductName = "LG UltraGear 27 inc QHD 165Hz Monitör"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            Description = "Son nesil işlemci ve yüksek çözünürlüklü ekranıyla üstün performans sunar. Uzun pil ömrü, gelişmiş bağlantı seçenekleri ve ergonomik tasarımıyla hem iş hem eğlence için idealdir.",
                            Image = "p55.jpeg",
                            IsActive = true,
                            IsHome = false,
                            Price = 15999.0,
                            ProductName = "Apple Watch Series 9 GPS 45mm"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "En yeni ürünler sizi bekliyor",
                            Image = "slider-1.jpeg",
                            Index = 0,
                            IsActive = true,
                            Title = "Yaz Koleksiyonu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Teknolojide en iyi fiyatlar",
                            Image = "slider-2.jpeg",
                            Index = 1,
                            IsActive = true,
                            Title = "Elektronik Fırsatları"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sezonun en şık modelleri",
                            Image = "slider-3.jpeg",
                            Index = 2,
                            IsActive = true,
                            Title = "Giyim Kampanyası"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_store.Models.CartItem", b =>
                {
                    b.HasOne("dotnet_store.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.HasOne("dotnet_store.Models.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("dotnet_store.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
